# Generated by Django 5.1.1 on 2024-09-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_intermediate_educationmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills_model',
            name='skill_name',
        ),
    ]
